# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/${PROJECT_ID}/run-cloud-build-trigger', '-f', 'Dockerfile', '.']

# Test without argument
- name: 'gcr.io/$PROJECT_ID/run-cloud-build-trigger'
  env: 'GOOGLE_APPLICATION_CREDENTIALS=gac.json'

# Test with argument
- name: 'gcr.io/$PROJECT_ID/run-cloud-build-trigger'
  env: 'GOOGLE_APPLICATION_CREDENTIALS'
  args: ['anothervariabletest']

# Push the image
images: ['gcr.io/${PROJECT_ID}/run-cloud-build-trigger']
